### ISSUE TITLE
Failed to create Gitlab identity provider

### ISSUE THREAD

**Issue by ichasco** [Apicurio/apicurio-keycloak-extensions#1]
Hi,
I have compiled the JAR and load in Keycloak. But when I configure it and save changes, it crashes:

```
 04:30:41,835 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-6) Uncaught server error: java.lang.AbstractMethodError: Receiver class io.apicurio.kc.ext.social.LocalGitLabIdentityProviderFactory does not define or inherit an implementation of the resolved method 'abstract org.keycloak.models.IdentityProviderModel createConfig()' of interface org.keycloak.broker.provider.IdentityProviderFactory.
```
Start command:
`command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled", "-Dapicurio.hub.gitlab.url=https://gitlab.example.com"`

Keycloak version: `9.0.2`
Gitlab version: `GitLab Community Edition 12.9.2`

Thanks

**Comment by EricWittmann** [comment]
What version of Keycloak are you using?  That identity provider class has not been updated for awhile, so it's probably a version mismatch issue.

**Comment by ichasco** [comment]
Hi,

Keycloak version: 9.0.2

**Comment by EricWittmann** [comment]
Yeah that's the issue.  Those identity provider classes were written for an older Keycloak version.  I can add this task to my to-do list, but if you have the ability to look into this yourself it'll probably get done sooner.  :)

Basically you would need to update the version of Keycloak in the `pom.xml` file and then fix whatever compiler problems that result.  

Also apologies for asking you a question that you had already included in the summary of the original problem report!  I just noticed... sigh
