### ISSUE TITLE
Generate release?

### ISSUE THREAD

**Issue by oblute** [Apicurio/apicurio-keycloak-extensions#5]
Would it be possible to generate a release for these extensions on github? Thanks!

**Comment by EricWittmann** [comment]
In progress right now.

**Comment by EricWittmann** [comment]
I set up a couple of GitHub Actions workflows for this (something we've been working on across the Apicurio projects).  One of those workflows is a Release workflow, which I triggered to generate a 9.0.1.Final release of this project. :)

Part of that should be a release into Central.  Give it an hour or two and hopefully it should be there!
